[tool.black]
line-length = 100
target-version = ['py36']

[tool.isort]
include_trailing_comma = "True"
extra_standard_library = ["dataclasses"]
known_third_party = ["pytest"]
line_length = 100
multi_line_output = 3
